android:
  components:
    - tools
    - emulator
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-28

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install six

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - npm install
    - cd src
    - npm run setup

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "10"
      script: "npm run ci.tslint"
    - stage: "WebPack"
      os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode10
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      before_script: pod repo update
      script: cd ../demo && tns build ios --bundle
    - language: android
      os: linux
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 10
      script: cd ../demo && tns build android --bundle
    - stage: "Build"
      env:
        - BuildAndroid="28"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 10
      script:
        - cd ../demo && tns build android
    - os: osx
      env:
        - BuildiOS="12"
        - Xcode="10"
      osx_image: xcode10
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      script:
        - cd ../demo && tns build ios
